# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_level',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
