# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='show_id',
            field=models.CharField(default=2, max_length=3),
        ),
    ]
